name: Install, CI, Deploy

on:
  push:
    branches:
      - main

jobs:
  install-ci-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set output vars
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: check that the var was set correctly
        run: echo "current version sha = ${{ steps.vars.outputs.sha_short }}"
      - name: update version.ts typescript file
        run: echo "export const version = \"${{ steps.vars.outputs.sha_short }}\";" > ./src/lib/version.ts
      - name: install packages
        run: npm install
      - name: lint
        run: npm ci
      - name: build and deploy Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.LIGHT_DOCKER_USER }}
          password: ${{ secrets.LIGHT_DOCKER_TOKEN }}
          tag_with_ref: true
          tag_with_sha:  true
          add_git_labels: true
          registry: ${{ secrets.LIGHT_DOCKER_REPOSITORY_URL }}
          repository: aads_vahub_mediation_analysis_scrollytelling

